required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen",
  "k8s.io/gengo/examples/deepcopy-gen",
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/gogo/protobuf/protoc-gen-gofast",
  "github.com/gogo/protobuf/protoc-gen-gogofast",
  "gopkg.in/src-d/go-git.v4"
]

[[override]]
  branch = "release-1.15"
  name = "k8s.io/api"

[[override]]
  branch = "release-1.15"
  name = "k8s.io/apimachinery"

[[override]]
  version = "v12.0.0"
  name = "k8s.io/client-go"

[[override]]
  name = "k8s.io/code-generator"
  branch = "release-1.15"

[[override]]
  name = "github.com/docker/docker"
  branch = "master"

[[override]]
  name = "k8s.io/kube-openapi"
  branch = "master"

[[constraint]]
  name = "k8s.io/gengo"
  revision = "b90029ef6cd877cb3f422d75b3a07707e3aac6b7"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
      name = "k8s.io/code-generator"
      unused-packages = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false

