/*
Copyright 2019 BlackRock, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ocibuilder/ocibuilder/pkg/apis/ocibuilder/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOCIBuilders implements OCIBuilderInterface
type FakeOCIBuilders struct {
	Fake *FakeOcibuilderV1alpha1
	ns   string
}

var ocibuildersResource = schema.GroupVersionResource{Group: "ocibuilder.com", Version: "v1alpha1", Resource: "ocibuilders"}

var ocibuildersKind = schema.GroupVersionKind{Group: "ocibuilder.com", Version: "v1alpha1", Kind: "OCIBuilder"}

// Get takes name of the oCIBuilder, and returns the corresponding oCIBuilder object, and an error if there is any.
func (c *FakeOCIBuilders) Get(name string, options v1.GetOptions) (result *v1alpha1.OCIBuilder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ocibuildersResource, c.ns, name), &v1alpha1.OCIBuilder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OCIBuilder), err
}

// List takes label and field selectors, and returns the list of OCIBuilders that match those selectors.
func (c *FakeOCIBuilders) List(opts v1.ListOptions) (result *v1alpha1.OCIBuilderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ocibuildersResource, ocibuildersKind, c.ns, opts), &v1alpha1.OCIBuilderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OCIBuilderList{ListMeta: obj.(*v1alpha1.OCIBuilderList).ListMeta}
	for _, item := range obj.(*v1alpha1.OCIBuilderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested oCIBuilders.
func (c *FakeOCIBuilders) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ocibuildersResource, c.ns, opts))

}

// Create takes the representation of a oCIBuilder and creates it.  Returns the server's representation of the oCIBuilder, and an error, if there is any.
func (c *FakeOCIBuilders) Create(oCIBuilder *v1alpha1.OCIBuilder) (result *v1alpha1.OCIBuilder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ocibuildersResource, c.ns, oCIBuilder), &v1alpha1.OCIBuilder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OCIBuilder), err
}

// Update takes the representation of a oCIBuilder and updates it. Returns the server's representation of the oCIBuilder, and an error, if there is any.
func (c *FakeOCIBuilders) Update(oCIBuilder *v1alpha1.OCIBuilder) (result *v1alpha1.OCIBuilder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ocibuildersResource, c.ns, oCIBuilder), &v1alpha1.OCIBuilder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OCIBuilder), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOCIBuilders) UpdateStatus(oCIBuilder *v1alpha1.OCIBuilder) (*v1alpha1.OCIBuilder, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ocibuildersResource, "status", c.ns, oCIBuilder), &v1alpha1.OCIBuilder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OCIBuilder), err
}

// Delete takes name of the oCIBuilder and deletes it. Returns an error if one occurs.
func (c *FakeOCIBuilders) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ocibuildersResource, c.ns, name), &v1alpha1.OCIBuilder{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOCIBuilders) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ocibuildersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.OCIBuilderList{})
	return err
}

// Patch applies the patch and returns the patched oCIBuilder.
func (c *FakeOCIBuilders) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.OCIBuilder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ocibuildersResource, c.ns, name, pt, data, subresources...), &v1alpha1.OCIBuilder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OCIBuilder), err
}
