/*
Copyright 2019 BlackRock, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/beval/beval/pkg/apis/beval/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// Fakebevals implements bevalInterface
type Fakebevals struct {
	Fake *FakebevalV1alpha1
	ns   string
}

var bevalsResource = schema.GroupVersionResource{Group: "beval.com", Version: "v1alpha1", Resource: "bevals"}

var bevalsKind = schema.GroupVersionKind{Group: "beval.com", Version: "v1alpha1", Kind: "beval"}

// Get takes name of the beval, and returns the corresponding beval object, and an error if there is any.
func (c *Fakebevals) Get(name string, options v1.GetOptions) (result *v1alpha1.beval, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bevalsResource, c.ns, name), &v1alpha1.beval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.beval), err
}

// List takes label and field selectors, and returns the list of bevals that match those selectors.
func (c *Fakebevals) List(opts v1.ListOptions) (result *v1alpha1.bevalList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bevalsResource, bevalsKind, c.ns, opts), &v1alpha1.bevalList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.bevalList{ListMeta: obj.(*v1alpha1.bevalList).ListMeta}
	for _, item := range obj.(*v1alpha1.bevalList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bevals.
func (c *Fakebevals) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bevalsResource, c.ns, opts))

}

// Create takes the representation of a beval and creates it.  Returns the server's representation of the beval, and an error, if there is any.
func (c *Fakebevals) Create(beval *v1alpha1.beval) (result *v1alpha1.beval, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bevalsResource, c.ns, beval), &v1alpha1.beval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.beval), err
}

// Update takes the representation of a beval and updates it. Returns the server's representation of the beval, and an error, if there is any.
func (c *Fakebevals) Update(beval *v1alpha1.beval) (result *v1alpha1.beval, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bevalsResource, c.ns, beval), &v1alpha1.beval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.beval), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *Fakebevals) UpdateStatus(beval *v1alpha1.beval) (*v1alpha1.beval, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bevalsResource, "status", c.ns, beval), &v1alpha1.beval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.beval), err
}

// Delete takes name of the beval and deletes it. Returns an error if one occurs.
func (c *Fakebevals) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bevalsResource, c.ns, name), &v1alpha1.beval{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *Fakebevals) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bevalsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.bevalList{})
	return err
}

// Patch applies the patch and returns the patched beval.
func (c *Fakebevals) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.beval, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bevalsResource, c.ns, name, pt, data, subresources...), &v1alpha1.beval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.beval), err
}
